### ISSUE TITLE
Opened attribute causes issues

### ISSUE THREAD

**Issue by bturk** [alijaya/iron-accordions#3]
When using the opened attribute there are a couple of behavioral issues:
1.  Clicking another collapsed item opens the new item but doesn't close the original item.
2.  Clicking the opened item doesn't close it the first time.

**Comment by alijaya** [comment]
Ah yes... This is because I use IronMultiSelectableBehavior for iron-accordions, the data of which is opened is one way from iron-accordions to iron-accordion, so if you change the opened from iron-accordion, thr model data in iron-accordions doesn't change (so it will cause an unexpected behaviour).

So the good way to set the initial value id from iron-accordions selected atttibute. So you set the selected attribute to the index which iron-accordion that you want to be opened. Or if you plan to make it multiple page opened in same time, use multi attribute and selectedValues attribute.

Hope this will clear things up.

**Comment by fluky** [comment]
That seems to do it, thanks.  Might want to update the doc to make this clear :).

**Comment by alijaya** [comment]
oh ok... sorry to make things confusing ._.
