### ISSUE TITLE
Add collapsable and action buttons in header

### ISSUE THREAD

**Issue by robertop87** [alijaya/iron-accordions#7]
Hi there:

It would be great have the next feature, one header could be customizable like next:

---------------------------------------------------------------------------------------
[Button1-Action1]  [Button2-Action2] [CollapserButton-ActionCollapse]
---------------------------------------------------------------------------------------

Then if the user press in Normal Buttons, the expected actions are performed, and we could set programatically the action to collapse the view (as accordion) whe user click on **CollapserButton**

It would be implemented, or if it's already done, let me know hot to do it

**Comment by alijaya** [comment]
Hi, nice idea... will look into it :D

**Comment by alijaya** [comment]
Hey, i've made separate branch, so I've migrated the code, so it will works with version 2.0 (so you need to use slot="header" rather than attribute header).

And I've made a simple class to trigger the effect `<iron-accordion-trigger>`.
To disable default behavior of the header, add `disable-header` attribute at `iron-accordion` element, see the demo.
